# Generated by Django 4.2.11 on 2024-03-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='project',
            field=models.ManyToManyField(to='api.project'),
        ),
    ]
