# Generated by Django 4.2.11 on 2024-09-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_envvar_key_alter_envvar_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Task',
        ),
        migrations.DeleteModel(
            name='AccountGroupMapping',
        ),
    ]
