# Generated by Django 4.2.11 on 2024-09-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_job_task_delete_accountgroupmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.project'),
            preserve_default=False,
        ),
    ]
