# Generated by Django 4.2.11 on 2024-09-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.pipeline'),
        ),
    ]
