# Generated by Django 4.2.11 on 2024-09-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stage_pipeline_alter_task_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='stages',
            field=models.ManyToManyField(to='api.stage'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'stage')},
        ),
    ]
