# Generated by Django 4.2.11 on 2024-09-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_stage_pipeline_pipeline_stages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='stages',
        ),
        migrations.AddField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.pipeline'),
        ),
    ]
