# Generated by Django 4.2.11 on 2024-09-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_pipeline_stages_stage_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='command',
            field=models.TextField(default='terraform init'),
            preserve_default=False,
        ),
    ]
