# Generated by Django 4.2.11 on 2024-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_task_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='stages',
            field=models.ManyToManyField(related_name='pipelines', to='api.stage'),
        ),
    ]
