# Generated by Django 4.2.11 on 2024-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_repo_branch_remove_repo_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repo',
            new_name='Git',
        ),
        migrations.RemoveField(
            model_name='scmpoll',
            name='webhook_secret',
        ),
        migrations.AddField(
            model_name='scmwebhook',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
