# Generated by Django 4.2.11 on 2024-10-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_repo_git_remove_scmpoll_webhook_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scmpoll',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='scmwebhook',
            name='repo',
        ),
        migrations.AddField(
            model_name='scmpoll',
            name='git',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='api.git'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scmwebhook',
            name='git',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='api.git'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='git',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='git', to='api.trigger'),
        ),
    ]
