# Generated by Django 4.2.11 on 2024-12-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_git_options_git_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='git',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='git', to='api.project'),
            preserve_default=False,
        ),
    ]
