# Generated by Django 4.2.11 on 2024-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_git_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='git',
            name='name',
            field=models.CharField(default='gitrepo1', max_length=255),
            preserve_default=False,
        ),
    ]
