# Generated by Django 4.2.11 on 2024-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_git_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
