# Generated by Django 4.2.11 on 2024-12-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_git_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='git',
            name='trigger',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
