# Generated by Django 4.2.11 on 2024-12-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_git_trigger_delete_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='git',
            name='fetch',
        ),
    ]
