# Generated by Django 4.2.11 on 2024-12-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_git_fetch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='git',
            name='ref',
        ),
        migrations.AddField(
            model_name='scmpoll',
            name='ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
