# Generated by Django 4.2.11 on 2024-12-15 15:28

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_git_ref_scmpoll_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('trigger_type', models.CharField(choices=[('artifact', 'Artifact'), (api.models.Git, 'Git'), ('manual', 'Manual'), ('secret', 'Secret')], max_length=25)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='api.project')),
            ],
        ),
    ]
