# Generated by Django 4.2.11 on 2024-12-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_artifact_git_trigger_delete_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.stage')),
            ],
        ),
        migrations.AlterField(
            model_name='artifact',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trigger'),
        ),
        migrations.AlterField(
            model_name='git',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trigger'),
        ),
    ]
