# Generated by Django 4.2.11 on 2024-12-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_trigger_alter_artifact_trigger_alter_git_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='stage',
        ),
        migrations.AddField(
            model_name='stage',
            name='trigger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trigger'),
        ),
    ]
