# Generated by Django 4.2.11 on 2024-12-16 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0028_remove_artifact_trigger_remove_git_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'api'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
