# Generated by Django 4.2.11 on 2024-12-16 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_stage_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='envvar',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
            preserve_default=False,
        ),
    ]
