# Generated by Django 5.1.4 on 2024-12-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_envvar_project'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'api'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
