# Generated by Django 5.1.4 on 2024-12-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_stage_content_type_alter_stage_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envvar',
            name='project',
        ),
    ]
