# Generated by Django 5.1.4 on 2024-12-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_envvar_project'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name_plural': 'environments'},
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='environments',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='object_id',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.environment'),
        ),
        migrations.CreateModel(
            name='StageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'app_label': 'api'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('environments', models.ManyToManyField(to='api.environment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stage')),
                ('on_fail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fail_set', to='api.stage')),
                ('on_success', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_set', to='api.stage')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.pipeline')),
                ('resources', models.ManyToManyField(to='api.git')),
            ],
        ),
    ]
