# Generated by Django 5.1.4 on 2024-12-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_environment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageattachment',
            name='environments',
            field=models.ManyToManyField(null=True, to='api.environment'),
        ),
        migrations.AlterField(
            model_name='stageattachment',
            name='resources',
            field=models.ManyToManyField(null=True, to='api.git'),
        ),
    ]
