# Generated by Django 5.1.4 on 2024-12-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_stageattachment_environments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='environments',
        ),
        migrations.AddField(
            model_name='environment',
            name='stages',
            field=models.ManyToManyField(to='api.stageattachment'),
        ),
        migrations.AlterField(
            model_name='stageattachment',
            name='environments',
            field=models.ManyToManyField(to='api.environment'),
        ),
        migrations.AlterField(
            model_name='stageattachment',
            name='resources',
            field=models.ManyToManyField(to='api.git'),
        ),
    ]
