# Generated by Django 5.1.4 on 2025-01-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_stage_environments_environment_stages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageattachment',
            name='environments',
        ),
        migrations.AlterField(
            model_name='environment',
            name='stages',
            field=models.ManyToManyField(related_name='environments', to='api.stageattachment'),
        ),
        migrations.AlterField(
            model_name='stageattachment',
            name='on_fail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_fail', to='api.stage'),
        ),
        migrations.AlterField(
            model_name='stageattachment',
            name='on_success',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_success', to='api.stage'),
        ),
    ]
