# Generated by Django 5.1.4 on 2025-01-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_stageattachment_environments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageattachment',
            name='resources',
        ),
    ]
