# Generated by Django 5.1.4 on 2025-01-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_stageattachment_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageattachment',
            name='resources',
            field=models.ManyToManyField(to='api.git'),
        ),
    ]
