# Generated by Django 5.1.4 on 2025-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_stageattachment_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='git',
            name='stages',
            field=models.ManyToManyField(to='api.stageattachment'),
        ),
    ]
