# Generated by Django 5.1.4 on 2025-01-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_stageattachment_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageattachment',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, to='api.git'),
        ),
    ]
