# Generated by Django 5.1.4 on 2025-01-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_stageattachment_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageattachment',
            name='resources',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.stageattachment')),
            ],
        ),
    ]
