# Generated by Django 5.1.4 on 2025-01-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_stageattachment_resources_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageattachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stageattachment',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
