# Generated by Django 4.2.5 on 2024-02-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('user', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, default='master', max_length=255)),
                ('shallow_clone', models.BooleanField(default=False)),
                ('fetch', models.CharField(choices=[('poll', 'Poll for changes'), ('push', 'Use webhook to listen for changes')], default='poll', max_length=4)),
            ],
        ),
    ]
