# Generated by Django 4.2.5 on 2024-03-11 02:40

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='branch',
        ),
        migrations.AlterField(
            model_name='repo',
            name='fetch',
            field=models.CharField(choices=[('poll', 'Poll for changes'), ('webhook', 'Use webhook to listen for changes')], default='poll', max_length=7),
        ),
        migrations.AlterField(
            model_name='repo',
            name='webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='scm.repo')),
            ],
        ),
    ]
